### ISSUE TITLE
List of (recent) DIY computer kits that use Z80 (Request for more test-case systems)

### ISSUE THREAD

**Issue by GaiusJocundus** [rejunity/z80-open-silicon#6]
This is a bit of an odd request, perhaps, but I think you'll see it makes sense.

I'm sure it's no surprise that there is a modern collection of new Z80 computer designs available; famously started with the rc2014 and less famously with the LiNC80. These systems have been dramatically improved upon in the Small Computer Central line of computers by Stephen C. Cousins.

There are other designs as well, notably the Zeal-8-Bit computer, with its memory manager and brand new, from scratch OS written in assembly and compiled with the z88dk toolchain.

These newer designs, some of which are brand new and some of which represent extended variations of historic designs, are quite robust and are used heavily in low-level computer education.

Small Computer Central is particularly important for having adopted, documented, extended, and developed peripherals for both the RCBus and Z50Bus; streamlining development for the community and empowering a great deal of third-party hardware extension by community members.

I believe that it would be wise for the project to, at the very least, highlight the RC2014 as a targeted platform. This would include the bulk of the Small Computer Central (SCC) designs as they are largely compatible. Including explicit callouts to other designs like LiNC80 -- which is a progenitor of other designs that are more popular; largely from SCC -- or Zeal-8-Bit Computer specifically may also help. Zeal-8-Bit is largely a new design but it represents a standard somewhat on par with the Commander X16.

I'm just setting up this issue as a suggestion for consideration, please feel free to close or ignore it at your discretion; if it is not an appropriate request for the project. I use these systems as daily drivers for both self-taught, low level computing education and for published educational works. To me they represent a modern standard for both vintage computing and modern, 8-bit software and hardware development.

Much obliged!

**Comment by rejunity** [comment]
Absolutely! @GaiusJocundus thank you for suggestion and pointers. I have updated README with the list and will keep an eye on those machines.

Once we have first chips I would be looking for beta testers who could try FOSS Z80 with recent DYI Z80 kits!

Please don't hesitate to contribute with more interesting machines for testing!

**Comment by tynemouthsoftware** [comment]
> Absolutely! @GaiusJocundus thank you for suggestion and pointers. I have updated README with the list and will keep an eye on those machines.
> 
> Once we have first chips I would be looking for beta testers who could try FOSS Z80 with recent DYI Z80 kits!
> 
> Please don't hesitate to contribute with more interesting machines for testing!

I designed the Minstrel 2, 3 and 4th kits that are based on the ZX80, ZX81 and Jupiter Ace respectively. All are Z80 based through hole self assembly kits. Now limited by the Z80 EOL, so would be interested to test out Z80 replacements in those. 

Thanks,

Dave

**Comment by GaiusJocundus** [comment]
> Absolutely! @GaiusJocundus thank you for suggestion and pointers. I have updated README with the list and will keep an eye on those machines.
> 
> Once we have first chips I would be looking for beta testers who could try FOSS Z80 with recent DYI Z80 kits!
> 
> Please don't hesitate to contribute with more interesting machines for testing!

Thank you so much! I'm very glad my suggestion proves helpful. I would love to be among the beta testers and have many devices to test with. I'll be able to test multiple operating systems, monitors, peripherals, and build toolchains and applications.

I very appreciate the work you're doing here, the Z80 should belong to the people at this point, anyway. EOL may have been the best thing for the community with teams like this picking up the project.

Much obliged!
